import React, { useState } from 'react';
import {
  AreaChart, Area, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, PieChart, Pie, Cell,
} from 'recharts';
import {
  Plus, Calendar, Download, Search, Filter, FileText, BarChart2, TrendingUp,
  Globe, Star, MapPin, Target, Users, ArrowUpRight, Eye, Edit3, Trash2,
  Send, Clock, CheckCircle, MoreHorizontal, ChevronRight,
} from 'lucide-react';
import SeoGmbProjectSelector from './SeoGmbProjectSelector';
import CrudTable from '../common/CrudTable';

// ── Chart Data ─────────────────────────────────────────────────────────────
const OVERVIEW_TREND = [
  { date: 'Apr 16', generated: 28, scheduled: 38, sent: 18 },
  { date: 'Apr 23', generated: 32, scheduled: 35, sent: 24 },
  { date: 'Apr 30', generated: 38, scheduled: 42, sent: 30 },
  { date: 'May 7', generated: 34, scheduled: 40, sent: 28 },
  { date: 'May 14', generated: 42, scheduled: 48, sent: 36 },
];

const REPORTS_BY_TYPE = [
  { name: 'SEO Reports', value: 28, pct: '19.7%', color: '#3B82F6' },
  { name: 'Audit Reports', value: 20, pct: '14.1%', color: '#10B981' },
  { name: 'Keyword Reports', value: 22, pct: '15.5%', color: '#F59E0B' },
  { name: 'Ranking Reports', value: 18, pct: '12.7%', color: '#8B5CF6' },
  { name: 'Backlink Reports', value: 14, pct: '9.9%', color: '#EF4444' },
  { name: 'Others', value: 40, pct: '28.2%', color: '#94A3B8' },
];

// ── Report Type Cards ──────────────────────────────────────────────────────
const REPORT_TYPES = [
  { name: 'SEO Reports', desc: 'Overview of overall SEO performance', reports: 12, scheduled: 4, icon: BarChart2, color: 'text-indigo-500 bg-indigo-50', key: 'seo' },
  { name: 'Website Audit Reports', desc: 'Technical SEO audit and analysis', reports: 8, scheduled: 2, icon: Target, color: 'text-emerald-500 bg-emerald-50', key: 'audit' },
  { name: 'Keyword Reports', desc: 'Keyword rankings and performance', reports: 10, scheduled: 5, icon: Search, color: 'text-amber-500 bg-amber-50', key: 'keyword' },
  { name: 'Ranking Reports', desc: 'Track keyword rankings over time', reports: 15, scheduled: 6, icon: TrendingUp, color: 'text-blue-500 bg-blue-50', key: 'ranking' },
  { name: 'Backlink Reports', desc: 'Backlink profile and analysis', reports: 10, scheduled: 3, icon: Globe, color: 'text-purple-500 bg-purple-50', key: 'backlink' },
  { name: 'Traffic Reports', desc: 'Website traffic and analytics', reports: 10, scheduled: 3, icon: Users, color: 'text-sky-500 bg-sky-50', key: 'traffic' },
  { name: 'GMB Reports', desc: 'Google Business Profile insights', reports: 7, scheduled: 2, icon: MapPin, color: 'text-rose-500 bg-rose-50', key: 'gmb' },
  { name: 'Review Reports', desc: 'Customer reviews and ratings', reports: 9, scheduled: 2, icon: Star, color: 'text-orange-500 bg-orange-50', key: 'review' },
  { name: 'Monthly Reports', desc: 'Monthly performance overview', reports: 24, scheduled: 6, icon: Calendar, color: 'text-teal-500 bg-teal-50', key: 'monthly' },
  { name: 'Quarterly Reports', desc: 'Quarterly performance summary', reports: 8, scheduled: 2, icon: BarChart2, color: 'text-cyan-500 bg-cyan-50', key: 'quarterly' },
  { name: 'Client Reports', desc: 'Client specific reports', reports: 18, scheduled: 5, icon: FileText, color: 'text-violet-500 bg-violet-50', key: 'client' },
  { name: 'Executive Reports', desc: 'High level executive summary', reports: 6, scheduled: 2, icon: BarChart2, color: 'text-pink-500 bg-pink-50', key: 'executive' },
];

// ── Column Definitions ─────────────────────────────────────────────────────
const recentReportCols = [
  { header: 'Report Name', accessor: 'name' },
  { header: 'Type', accessor: 'type' },
  { header: 'Client/Project', accessor: 'client' },
  { header: 'Date Generated', accessor: 'date' },
  { header: 'Generated By', accessor: 'by' },
  { header: 'Format', accessor: 'format' },
  { header: 'Status', accessor: 'status' },
];

const makeReportCols = (type) => [
  { header: 'Report Name', accessor: 'name' },
  { header: 'Client/Project', accessor: 'client' },
  { header: 'Date Generated', accessor: 'date' },
  { header: 'Generated By', accessor: 'by' },
  { header: 'Format', accessor: 'format' },
  { header: 'Status', accessor: 'status' },
];

const templateCols = [
  { header: 'Template Name', accessor: 'name' },
  { header: 'Type', accessor: 'type' },
  { header: 'Sections', accessor: 'sections' },
  { header: 'Last Used', accessor: 'used' },
  { header: 'Status', accessor: 'status' },
];

const scheduleCols = [
  { header: 'Schedule Name', accessor: 'name' },
  { header: 'Report Type', accessor: 'type' },
  { header: 'Frequency', accessor: 'frequency' },
  { header: 'Recipients', accessor: 'recipients' },
  { header: 'Next Send', accessor: 'next' },
  { header: 'Status', accessor: 'status' },
];

const clientCols = [
  { header: 'Client', accessor: 'client' },
  { header: 'Reports', accessor: 'reports' },
  { header: 'Last Report', accessor: 'last' },
  { header: 'Status', accessor: 'status' },
];

const executiveCols = [
  { header: 'Report Name', accessor: 'name' },
  { header: 'Period', accessor: 'period' },
  { header: 'Client', accessor: 'client' },
  { header: 'Date', accessor: 'date' },
  { header: 'Status', accessor: 'status' },
];

// ── Initial Data ───────────────────────────────────────────────────────────
const INIT = {
  recent: [
    { id: 1, name: 'May 2026 SEO Performance Report', type: 'SEO Report', client: 'ABC Digital Solutions', date: 'May 14, 2026 10:30 AM', by: 'John Smith', format: 'PDF', status: 'Sent' },
    { id: 2, name: 'Website Audit Report - May 2026', type: 'Audit Report', client: 'Growth Marketing Co.', date: 'May 14, 2026 09:15 AM', by: 'Sarah Johnson', format: 'PDF', status: 'Sent' },
    { id: 3, name: 'Keyword Ranking Report - Week 19', type: 'Keyword Report', client: 'Tech Solutions Inc.', date: 'May 13, 2026 04:45 PM', by: 'Mike Brown', format: 'PDF', status: 'Scheduled' },
    { id: 4, name: 'Backlink Analysis Report - May 2026', type: 'Backlink Report', client: 'Web Innovators', date: 'May 13, 2026 02:20 PM', by: 'Emily Davis', format: 'PDF', status: 'Sent' },
    { id: 5, name: 'GMB Performance Report - May 2026', type: 'GMB Report', client: 'Digital Boosters', date: 'May 12, 2026 11:10 AM', by: 'David Wilson', format: 'PDF', status: 'Sent' },
    { id: 6, name: 'Monthly Traffic Overview - Apr 2026', type: 'Traffic Report', client: 'ABC Digital Solutions', date: 'May 10, 2026 09:00 AM', by: 'John Smith', format: 'PDF', status: 'Sent' },
    { id: 7, name: 'Q1 2026 Executive Summary', type: 'Executive Report', client: 'Growth Marketing Co.', date: 'May 8, 2026 02:00 PM', by: 'Sarah Johnson', format: 'PDF', status: 'Sent' },
  ],
  seo: [
    { id: 1, name: 'May 2026 SEO Performance Report', client: 'ABC Digital Solutions', date: 'May 14, 2026', by: 'John Smith', format: 'PDF', status: 'Sent' },
    { id: 2, name: 'SEO Health Check - May 2026', client: 'Growth Marketing Co.', date: 'May 12, 2026', by: 'Mike Brown', format: 'PDF', status: 'Scheduled' },
    { id: 3, name: 'Monthly SEO Summary', client: 'Tech Solutions Inc.', date: 'May 10, 2026', by: 'Emily Davis', format: 'XLSX', status: 'Sent' },
  ],
  audit: [
    { id: 1, name: 'Website Audit Report - May 2026', client: 'Growth Marketing Co.', date: 'May 14, 2026', by: 'Sarah Johnson', format: 'PDF', status: 'Sent' },
    { id: 2, name: 'Technical SEO Audit - Q2', client: 'Web Innovators', date: 'May 8, 2026', by: 'Mike Brown', format: 'PDF', status: 'Sent' },
  ],
  keyword: [
    { id: 1, name: 'Keyword Ranking Report - Week 19', client: 'Tech Solutions Inc.', date: 'May 13, 2026', by: 'Mike Brown', format: 'PDF', status: 'Scheduled' },
    { id: 2, name: 'Top Keywords Monthly Report', client: 'ABC Digital Solutions', date: 'May 10, 2026', by: 'John Smith', format: 'PDF', status: 'Sent' },
    { id: 3, name: 'Long-tail Keyword Analysis', client: 'Digital Boosters', date: 'May 8, 2026', by: 'Emily Davis', format: 'XLSX', status: 'Sent' },
  ],
  ranking: [
    { id: 1, name: 'Ranking Overview - May 2026', client: 'ABC Digital Solutions', date: 'May 14, 2026', by: 'John Smith', format: 'PDF', status: 'Sent' },
    { id: 2, name: 'City-level Rankings Q2 Report', client: 'Web Innovators', date: 'May 11, 2026', by: 'Sarah Johnson', format: 'PDF', status: 'Sent' },
    { id: 3, name: 'Device Ranking Comparison', client: 'Tech Solutions Inc.', date: 'May 9, 2026', by: 'Mike Brown', format: 'PDF', status: 'Scheduled' },
  ],
  backlink: [
    { id: 1, name: 'Backlink Analysis Report - May 2026', client: 'Web Innovators', date: 'May 13, 2026', by: 'Emily Davis', format: 'PDF', status: 'Sent' },
    { id: 2, name: 'New Backlinks This Month', client: 'ABC Digital Solutions', date: 'May 10, 2026', by: 'John Smith', format: 'PDF', status: 'Sent' },
  ],
  traffic: [
    { id: 1, name: 'Monthly Traffic Overview - Apr 2026', client: 'ABC Digital Solutions', date: 'May 10, 2026', by: 'John Smith', format: 'PDF', status: 'Sent' },
    { id: 2, name: 'Organic vs Paid Traffic Analysis', client: 'Digital Boosters', date: 'May 7, 2026', by: 'David Wilson', format: 'XLSX', status: 'Sent' },
  ],
  gmb: [
    { id: 1, name: 'GMB Performance Report - May 2026', client: 'Digital Boosters', date: 'May 12, 2026', by: 'David Wilson', format: 'PDF', status: 'Sent' },
    { id: 2, name: 'GMB Insights Monthly Report', client: 'Tech Solutions Inc.', date: 'May 5, 2026', by: 'Mike Brown', format: 'PDF', status: 'Sent' },
  ],
  review: [
    { id: 1, name: 'Review Analysis - May 2026', client: 'ABC Digital Solutions', date: 'May 11, 2026', by: 'John Smith', format: 'PDF', status: 'Sent' },
    { id: 2, name: 'Customer Sentiment Report', client: 'Growth Marketing Co.', date: 'May 6, 2026', by: 'Sarah Johnson', format: 'PDF', status: 'Scheduled' },
  ],
  monthly: [
    { id: 1, name: 'Monthly SEO Summary - May 2026', client: 'ABC Digital Solutions', date: 'May 14, 2026', by: 'John Smith', format: 'PDF', status: 'Sent' },
    { id: 2, name: 'Monthly Analytics Overview - May', client: 'Growth Marketing Co.', date: 'May 14, 2026', by: 'Sarah Johnson', format: 'PDF', status: 'Sent' },
    { id: 3, name: 'May 2026 Full Performance Report', client: 'Tech Solutions Inc.', date: 'May 13, 2026', by: 'Emily Davis', format: 'PDF', status: 'Scheduled' },
  ],
  quarterly: [
    { id: 1, name: 'Q1 2026 SEO Summary', client: 'ABC Digital Solutions', date: 'Apr 5, 2026', by: 'John Smith', format: 'PDF', status: 'Sent' },
    { id: 2, name: 'Q1 2026 Performance Overview', client: 'Growth Marketing Co.', date: 'Apr 3, 2026', by: 'Sarah Johnson', format: 'PDF', status: 'Sent' },
  ],
  client: [
    { id: 1, name: 'ABC Digital - Monthly Report', client: 'ABC Digital Solutions', date: 'May 14, 2026', by: 'John Smith', format: 'PDF', status: 'Sent' },
    { id: 2, name: 'Growth Marketing Monthly', client: 'Growth Marketing Co.', date: 'May 13, 2026', by: 'Sarah Johnson', format: 'PDF', status: 'Sent' },
    { id: 3, name: 'Tech Solutions Weekly Report', client: 'Tech Solutions Inc.', date: 'May 12, 2026', by: 'Mike Brown', format: 'PDF', status: 'Scheduled' },
  ],
  executive: [
    { id: 1, name: 'Q1 2026 Executive Summary', client: 'Growth Marketing Co.', date: 'May 8, 2026', by: 'Sarah Johnson', format: 'PDF', status: 'Sent' },
    { id: 2, name: 'Board Report - May 2026', client: 'ABC Digital Solutions', date: 'May 5, 2026', by: 'John Smith', format: 'PDF', status: 'Sent' },
  ],
  templates: [
    { id: 1, name: 'Monthly SEO Report', type: 'SEO Report', sections: '8', used: 'May 14, 2026', status: 'Active' },
    { id: 2, name: 'Website Audit Template', type: 'Audit Report', sections: '12', used: 'May 14, 2026', status: 'Active' },
    { id: 3, name: 'GMB Performance Report', type: 'GMB Report', sections: '6', used: 'May 12, 2026', status: 'Active' },
    { id: 4, name: 'Executive Summary', type: 'Executive Report', sections: '5', used: 'May 8, 2026', status: 'Active' },
    { id: 5, name: 'Client Monthly Report', type: 'Client Report', sections: '10', used: 'May 10, 2026', status: 'Active' },
  ],
  schedules: [
    { id: 1, name: 'ABC Digital Monthly', type: 'SEO Report', frequency: 'Monthly', recipients: '3 contacts', next: 'Jun 1, 2026', status: 'Active' },
    { id: 2, name: 'Weekly Rank Report', type: 'Keyword Report', frequency: 'Weekly', recipients: '2 contacts', next: 'May 22, 2026', status: 'Active' },
    { id: 3, name: 'GMB Weekly Insights', type: 'GMB Report', frequency: 'Weekly', recipients: '1 contact', next: 'May 22, 2026', status: 'Active' },
    { id: 4, name: 'Quarterly Board Report', type: 'Executive Report', frequency: 'Quarterly', recipients: '5 contacts', next: 'Jul 1, 2026', status: 'Active' },
    { id: 5, name: 'Monthly Traffic Summary', type: 'Traffic Report', frequency: 'Monthly', recipients: '4 contacts', next: 'Jun 1, 2026', status: 'Paused' },
  ],
  clients: [
    { id: 1, client: 'ABC Digital Solutions', reports: '18', last: 'May 14, 2026', status: 'Sent' },
    { id: 2, client: 'Growth Marketing Co.', reports: '15', last: 'May 13, 2026', status: 'Sent' },
    { id: 3, client: 'Tech Solutions Inc.', reports: '12', last: 'May 12, 2026', status: 'Scheduled' },
    { id: 4, client: 'Web Innovators', reports: '10', last: 'May 9, 2026', status: 'Sent' },
    { id: 5, client: 'Digital Boosters', reports: '8', last: 'May 8, 2026', status: 'Scheduled' },
  ],
};

// ── Tabs ───────────────────────────────────────────────────────────────────
const MAIN_TABS = [
  { id: 'All Reports', icon: BarChart2 },
  { id: 'SEO Reports', icon: TrendingUp },
  { id: 'Client Reports', icon: Users },
  { id: 'Executive Reports', icon: FileText },
  { id: 'Templates', icon: Target },
  { id: 'Schedules', icon: Clock },
];

// Each "All Reports" sub-section maps to a report type card key
const TYPE_TO_KEY = {
  'SEO Reports': 'seo', 'Website Audit Reports': 'audit', 'Keyword Reports': 'keyword',
  'Ranking Reports': 'ranking', 'Backlink Reports': 'backlink', 'Traffic Reports': 'traffic',
  'GMB Reports': 'gmb', 'Review Reports': 'review', 'Monthly Reports': 'monthly',
  'Quarterly Reports': 'quarterly', 'Client Reports': 'client', 'Executive Reports': 'executive',
};

// ── Status Badge ───────────────────────────────────────────────────────────
const sBadge = (s) => {
  const m = { Sent: 'bg-emerald-50 text-emerald-700 border border-emerald-200', Scheduled: 'bg-amber-50 text-amber-700 border border-amber-200', Active: 'bg-emerald-50 text-emerald-700 border border-emerald-200', Paused: 'bg-slate-100 text-slate-500', Draft: 'bg-slate-100 text-slate-500' };
  return <span className={`text-xs  px-2.5 py-0.5 rounded-full ${m[s] || 'bg-slate-100 text-slate-500'}`}>{s}</span>;
};

// ═══════════════════════════════════════════════════════════════════════════
export default function SeoGmbReportsPage() {
  const [activeTab, setActiveTab] = useState('All Reports');
  const [searchQ, setSearchQ] = useState('');
  const [tableData, setTableData] = useState(INIT);
  const [project, setProject] = useState(null);

  const makeAdd = (k) => (item) => setTableData(prev => ({ ...prev, [k]: [...prev[k], { ...item, id: prev[k].length ? Math.max(...prev[k].map(i => i.id)) + 1 : 1 }] }));
  const makeEdit = (k) => (id, item) => setTableData(prev => ({ ...prev, [k]: prev[k].map(i => i.id === id ? { ...i, ...item } : i) }));
  const makeDel = (k) => (id) => setTableData(prev => ({ ...prev, [k]: prev[k].filter(i => i.id !== id) }));

  const loadProject = async (p) => {
    try { const r = await fetch(`http://localhost:5000/api/projects/${p.id}`); if (r.ok) setProject(await r.json()); } catch { }
  };

  const filtered = tableData.recent.filter(r =>
    r.name.toLowerCase().includes(searchQ.toLowerCase()) ||
    r.client.toLowerCase().includes(searchQ.toLowerCase()) ||
    r.type.toLowerCase().includes(searchQ.toLowerCase())
  );

  return (
    <div className="bg-slate-50 min-h-screen font-sans pb-10">

      {/* ── Header ── */}
      <div className="bg-white border-b border-slate-200 py-3.5 px-6 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 bg-blue-50 border border-blue-100 rounded flex items-center justify-center">
            <FileText size={16} className="text-blue-500" />
          </div>
          <div>
            <h1 className="text-base  text-slate-900 m-0 leading-none">Reports {project ? `for ${project.name}` : ''}</h1>
            <p className="text-xs text-slate-400 m-0 mt-0.5">Generate and manage comprehensive SEO reports for your website and clients.</p>
          </div>
          <SeoGmbProjectSelector onProjectChange={loadProject} />
        </div>
        <div className="flex items-center gap-2">
          <button className="bg-white hover:bg-slate-50 border border-slate-200 text-slate-700 rounded px-3 py-2 text-xs  flex items-center gap-1.5 cursor-pointer">
            <Calendar size={13} /> May 8 – May 15, 2026
          </button>
          <button className="bg-white hover:bg-slate-50 border border-slate-200 text-slate-700 rounded px-3 py-2 text-xs  flex items-center gap-1.5 cursor-pointer">
            <Download size={13} /> Export All Reports
          </button>
          <button className="bg-blue-500 hover:bg-blue-600 border-none text-white rounded px-4 py-2 text-xs  flex items-center gap-1.5 cursor-pointer transition-colors">
            <Plus size={14} /> Create Custom Report
          </button>
        </div>
      </div>

      <div className="px-6 py-4">

        {/* ── Tab Bar ── */}
        <div className="flex gap-1 mb-5 bg-white p-1 rounded border border-slate-200 overflow-x-auto whitespace-nowrap scrollbar-none">
          {MAIN_TABS.map(({ id, icon: Icon }) => (
            <button key={id} onClick={() => setActiveTab(id)}
              className={`flex items-center gap-1.5 py-2.5 px-4 rounded text-xs  cursor-pointer border-none outline-none transition-all shrink-0 ${activeTab === id ? 'bg-blue-50 text-blue-600 shadow-sm' : 'text-slate-500 hover:bg-slate-50'}`}
            >
              <Icon size={12} /> {id}
            </button>
          ))}
        </div>

        {/* ═══════════════════ ALL REPORTS ═══════════════════ */}
        {activeTab === 'All Reports' && (
          <div className="flex flex-col gap-5">

            {/* 12 Report Type Cards */}
            <div className="grid grid-cols-6 gap-4">
              {REPORT_TYPES.map((rt) => (
                <div key={rt.name} className="bg-white rounded-2xl border border-slate-200 p-4 hover:shadow-md transition-shadow cursor-pointer" onClick={() => setActiveTab(rt.name === 'Client Reports' ? 'Client Reports' : rt.name === 'Executive Reports' ? 'Executive Reports' : rt.name === 'SEO Reports' ? 'SEO Reports' : rt.name)}>
                  <div className="flex items-center gap-2 mb-2">
                    <div className={`w-7 h-7 rounded flex items-center justify-center ${rt.color}`}><rt.icon size={13} /></div>
                    <p className="text-xs  text-slate-800 m-0 leading-tight">{rt.name}</p>
                  </div>
                  <p className="text-[9px] text-slate-400 m-0 mb-2 leading-relaxed">{rt.desc}</p>
                  <div className="flex items-center gap-3 mb-2">
                    <div><strong className="text-lg font-black text-slate-900">{rt.reports}</strong><span className="text-[9px] text-slate-400 ml-1">Reports</span></div>
                    <div><strong className="text-lg font-black text-slate-500">{rt.scheduled}</strong><span className="text-[9px] text-slate-400 ml-1">Scheduled</span></div>
                  </div>
                  <button className="text-blue-500 text-[9px]  border-none bg-transparent cursor-pointer p-0 hover:underline">View Reports →</button>
                </div>
              ))}
            </div>

            {/* Charts Row + Top Clients */}
            <div className="grid grid-cols-3 gap-5">
              {/* Reports Overview */}
              <div className="col-span-1 bg-white rounded-2xl border border-slate-200 p-5">
                <div className="flex justify-between items-center mb-3">
                  <h3 className="text-sm  text-slate-900 m-0">Reports Overview</h3>
                  <span className="text-xs border border-slate-200 rounded px-2 py-0.5 text-slate-400 ">Last 30 Days ▾</span>
                </div>
                <div className="flex gap-3 mb-2 text-xs  text-slate-500">
                  {[{ l: 'Generated', c: '#3B82F6' }, { l: 'Scheduled', c: '#8B5CF6' }, { l: 'Sent', c: '#10B981' }].map(d => (
                    <span key={d.l} className="flex items-center gap-1"><span className="w-3 h-0.5 inline-block" style={{ backgroundColor: d.c }} />{d.l}</span>
                  ))}
                </div>
                <ResponsiveContainer width="100%" height={150}>
                  <AreaChart data={OVERVIEW_TREND}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#F1F5F9" />
                    <XAxis dataKey="date" tick={{ fontSize: 8, fill: '#94A3B8' }} />
                    <YAxis tick={{ fontSize: 8, fill: '#94A3B8' }} />
                    <Tooltip />
                    <Area type="monotone" dataKey="generated" stroke="#3B82F6" fill="#DBEAFE" strokeWidth={2} name="Generated" />
                    <Area type="monotone" dataKey="scheduled" stroke="#8B5CF6" fill="#EDE9FE" strokeWidth={2} name="Scheduled" />
                    <Area type="monotone" dataKey="sent" stroke="#10B981" fill="#D1FAE5" strokeWidth={2} name="Sent" />
                  </AreaChart>
                </ResponsiveContainer>
                <div className="grid grid-cols-5 gap-1 mt-3 pt-3 border-t border-slate-100">
                  {[
                    { l: 'Reports\nGenerated', v: '142', c: '+18.4%' },
                    { l: 'Reports\nScheduled', v: '48', c: '+15.4%' },
                    { l: 'Reports\nSent', v: '126', c: '+20.1%' },
                    { l: 'Report\nOpens', v: '98', c: '+18.3%' },
                    { l: 'Downloads', v: '76', c: '+11.8%' },
                  ].map((s, i) => (
                    <div key={i} className="text-center">
                      <strong className="text-xs font-black text-slate-900 block">{s.v}</strong>
                      <span className="text-[8px] text-slate-400  whitespace-pre-line leading-tight">{s.l}</span>
                      <span className="text-[8px] text-emerald-500  flex items-center justify-center gap-0.5 mt-0.5"><ArrowUpRight size={8} />{s.c}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Reports by Type donut */}
              <div className="col-span-1 bg-white rounded-2xl border border-slate-200 p-5">
                <h3 className="text-sm  text-slate-900 m-0 mb-3">Reports by Type</h3>
                <div className="flex items-center gap-4">
                  <div className="relative flex-shrink-0">
                    <ResponsiveContainer width={130} height={130}>
                      <PieChart>
                        <Pie data={REPORTS_BY_TYPE} cx="50%" cy="50%" innerRadius={38} outerRadius={58} dataKey="value" paddingAngle={2}>
                          {REPORTS_BY_TYPE.map((e, i) => <Cell key={i} fill={e.color} />)}
                        </Pie>
                      </PieChart>
                    </ResponsiveContainer>
                    <div className="absolute inset-0 flex flex-col items-center justify-center">
                      <strong className="text-base font-black text-slate-900">142</strong>
                      <span className="text-[8px] text-slate-400">Total Reports</span>
                    </div>
                  </div>
                  <div className="flex flex-col gap-1.5 flex-1">
                    {REPORTS_BY_TYPE.map((d) => (
                      <div key={d.name} className="flex items-center justify-between text-xs">
                        <div className="flex items-center gap-1"><span className="w-2 h-2 rounded-full" style={{ backgroundColor: d.color }} /><span className="text-slate-600">{d.name}</span></div>
                        <div><strong className="text-slate-800">{d.value}</strong><span className="text-slate-400 ml-1">({d.pct})</span></div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* Top Clients */}
              <div className="col-span-1 bg-white rounded-2xl border border-slate-200 p-5">
                <div className="flex justify-between items-center mb-3">
                  <h3 className="text-sm  text-slate-900 m-0">Top Clients <span className="text-slate-400 font-normal text-xs">(By Reports)</span></h3>
                </div>
                <table className="w-full text-xs text-slate-700">
                  <thead>
                    <tr className="text-[9px] text-slate-400  uppercase border-b border-slate-100">
                      <th className="pb-1.5 text-left">Client</th>
                      <th className="pb-1.5 text-center">Reports</th>
                      <th className="pb-1.5 text-center">Last Report</th>
                      <th className="pb-1.5 text-center">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {tableData.clients.map(c => (
                      <tr key={c.id} className="border-b border-slate-50">
                        <td className="py-1.5  text-slate-800">{c.client}</td>
                        <td className="py-1.5 text-center font-black text-slate-900">{c.reports}</td>
                        <td className="py-1.5 text-center text-slate-500">{c.last}</td>
                        <td className="py-1.5 text-center">{sBadge(c.status)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
                <button onClick={() => setActiveTab('Client Reports')} className="w-full text-center text-blue-500 text-xs  border-none bg-transparent cursor-pointer hover:underline mt-2">View All Clients →</button>
              </div>
            </div>

            {/* Recent Reports Table */}
            <div className="bg-white rounded-2xl border border-slate-200 p-5">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-sm  text-slate-900 m-0">Recent Reports</h3>
                <div className="flex items-center gap-2">
                  <div className="relative">
                    <Search size={13} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-400" />
                    <input value={searchQ} onChange={e => setSearchQ(e.target.value)} placeholder="Search reports..." className="border border-slate-200 rounded pl-7 pr-3 py-1.5 text-xs text-slate-700 focus:border-blue-400 outline-none w-48" />
                  </div>
                  <button className="bg-white hover:bg-slate-50 border border-slate-200 text-slate-600 rounded px-3 py-1.5 text-xs  flex items-center gap-1.5 cursor-pointer">
                    <Filter size={12} /> Filters
                  </button>
                  <button
                    onClick={() => makeAdd('recent')({ name: 'New Report', type: 'SEO Report', client: 'ABC Digital', date: new Date().toLocaleDateString(), by: 'John Smith', format: 'PDF', status: 'Draft' })}
                    className="bg-blue-500 hover:bg-blue-600 border-none text-white rounded px-3 py-1.5 text-xs  flex items-center gap-1.5 cursor-pointer transition-colors"
                  >
                    <Plus size={13} /> Create Report
                  </button>
                </div>
              </div>

              <table className="w-full text-xs text-slate-700">
                <thead>
                  <tr className="text-xs text-slate-400  uppercase border-b border-slate-200 bg-slate-50">
                    <th className="py-2 px-3 text-left">Report Name</th>
                    <th className="py-2 px-3 text-left">Type</th>
                    <th className="py-2 px-3 text-left">Client / Project</th>
                    <th className="py-2 px-3 text-left">Date Generated</th>
                    <th className="py-2 px-3 text-left">Generated By</th>
                    <th className="py-2 px-3 text-center">Format</th>
                    <th className="py-2 px-3 text-center">Status</th>
                    <th className="py-2 px-3 text-center">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {filtered.map((row) => (
                    <tr key={row.id} className="border-b border-slate-100 hover:bg-slate-50/50 transition-colors">
                      <td className="py-2.5 px-3">
                        <div className="flex items-center gap-2">
                          <div className="w-6 h-6 bg-blue-50 rounded flex items-center justify-center flex-shrink-0"><FileText size={11} className="text-blue-500" /></div>
                          <span className=" text-slate-800 truncate max-w-[180px]">{row.name}</span>
                        </div>
                      </td>
                      <td className="py-2.5 px-3">
                        <div className="flex items-center gap-1 text-slate-500"><FileText size={10} /> {row.type}</div>
                      </td>
                      <td className="py-2.5 px-3 text-slate-600">{row.client}</td>
                      <td className="py-2.5 px-3 text-slate-500">{row.date}</td>
                      <td className="py-2.5 px-3">
                        <div className="flex items-center gap-1.5">
                          <div className="w-5 h-5 rounded-full bg-blue-100 flex items-center justify-center text-[9px] font-black text-blue-600">{row.by[0]}</div>
                          <span className="text-slate-600">{row.by}</span>
                        </div>
                      </td>
                      <td className="py-2.5 px-3 text-center">
                        <span className="text-[9px]  text-rose-600 bg-rose-50 border border-rose-200 px-2 py-0.5 rounded">{row.format}</span>
                      </td>
                      <td className="py-2.5 px-3 text-center">{sBadge(row.status)}</td>
                      <td className="py-2.5 px-3">
                        <div className="flex items-center justify-center gap-1.5">
                          <button className="w-6 h-6 bg-slate-50 hover:bg-blue-50 rounded flex items-center justify-center cursor-pointer border border-slate-200 hover:border-blue-200 transition-colors"><Eye size={11} className="text-slate-500" /></button>
                          <button className="w-6 h-6 bg-slate-50 hover:bg-slate-100 rounded flex items-center justify-center cursor-pointer border border-slate-200 transition-colors"><Download size={11} className="text-slate-500" /></button>
                          <button className="w-6 h-6 bg-slate-50 hover:bg-amber-50 rounded flex items-center justify-center cursor-pointer border border-slate-200 hover:border-amber-200 transition-colors" onClick={() => makeEdit('recent')(row.id, { status: 'Sent' })}><Edit3 size={11} className="text-slate-500" /></button>
                          <button className="w-6 h-6 bg-slate-50 hover:bg-rose-50 rounded flex items-center justify-center cursor-pointer border border-slate-200 hover:border-rose-200 transition-colors" onClick={() => makeDel('recent')(row.id)}><Trash2 size={11} className="text-slate-500" /></button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>

              <div className="flex items-center justify-between mt-3 pt-3 border-t border-slate-100">
                <p className="text-xs text-slate-400 m-0">Showing 1 to {filtered.length} of 142 results</p>
                <div className="flex items-center gap-4">
                  <div className="flex items-center gap-1">
                    {['‹', 1, 2, 3, 4, 5, '…', 29, '›'].map((p, i) => (
                      <button key={i} className={`w-7 h-7 rounded text-xs  border-none cursor-pointer ${p === 1 ? 'bg-blue-500 text-white' : 'bg-white text-slate-500 hover:bg-slate-100 border border-slate-200'}`}>{p}</button>
                    ))}
                  </div>
                  <div className="flex items-center gap-1 text-xs text-slate-400">
                    Rows per page:
                    <select className="border border-slate-200 rounded px-1 py-0.5 text-slate-700 text-xs outline-none">
                      <option>5</option><option>10</option><option>25</option>
                    </select>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ═══════════════════ SEO REPORTS ═══════════════════ */}
        {activeTab === 'SEO Reports' && (
          <div className="flex flex-col gap-5">
            <div className="grid grid-cols-4 gap-4">
              {[{ l: 'Total SEO Reports', v: '12', c: 'This Month' }, { l: 'Scheduled', v: '4', c: 'Upcoming' }, { l: 'Clients Covered', v: '5', c: 'Active' }, { l: 'Avg. Open Rate', v: '76%', c: '+8.2%' }].map(s => (
                <div key={s.l} className="bg-white rounded-2xl p-4 border border-slate-200">
                  <span className="text-xs text-slate-400  block">{s.l}</span>
                  <strong className="text-2xl font-black text-slate-900 block mt-1">{s.v}</strong>
                  <span className="text-xs text-emerald-500  mt-1 block">{s.c}</span>
                </div>
              ))}
            </div>
            <CrudTable title="SEO Reports" columns={makeReportCols('seo')} data={tableData.seo} onAdd={makeAdd('seo')} onEdit={makeEdit('seo')} onDelete={makeDel('seo')} />
            <div className="grid grid-cols-3 gap-4">
              <CrudTable title="Website Audit Reports" columns={makeReportCols('audit')} data={tableData.audit} onAdd={makeAdd('audit')} onEdit={makeEdit('audit')} onDelete={makeDel('audit')} />
              <CrudTable title="Keyword Reports" columns={makeReportCols('keyword')} data={tableData.keyword} onAdd={makeAdd('keyword')} onEdit={makeEdit('keyword')} onDelete={makeDel('keyword')} />
              <CrudTable title="Ranking Reports" columns={makeReportCols('ranking')} data={tableData.ranking} onAdd={makeAdd('ranking')} onEdit={makeEdit('ranking')} onDelete={makeDel('ranking')} />
            </div>
            <div className="grid grid-cols-3 gap-4">
              <CrudTable title="Backlink Reports" columns={makeReportCols('backlink')} data={tableData.backlink} onAdd={makeAdd('backlink')} onEdit={makeEdit('backlink')} onDelete={makeDel('backlink')} />
              <CrudTable title="Traffic Reports" columns={makeReportCols('traffic')} data={tableData.traffic} onAdd={makeAdd('traffic')} onEdit={makeEdit('traffic')} onDelete={makeDel('traffic')} />
              <CrudTable title="GMB Reports" columns={makeReportCols('gmb')} data={tableData.gmb} onAdd={makeAdd('gmb')} onEdit={makeEdit('gmb')} onDelete={makeDel('gmb')} />
            </div>
            <div className="grid grid-cols-3 gap-4">
              <CrudTable title="Review Reports" columns={makeReportCols('review')} data={tableData.review} onAdd={makeAdd('review')} onEdit={makeEdit('review')} onDelete={makeDel('review')} />
              <CrudTable title="Monthly Reports" columns={makeReportCols('monthly')} data={tableData.monthly} onAdd={makeAdd('monthly')} onEdit={makeEdit('monthly')} onDelete={makeDel('monthly')} />
              <CrudTable title="Quarterly Reports" columns={makeReportCols('quarterly')} data={tableData.quarterly} onAdd={makeAdd('quarterly')} onEdit={makeEdit('quarterly')} onDelete={makeDel('quarterly')} />
            </div>
          </div>
        )}

        {/* ═══════════════════ CLIENT REPORTS ═══════════════════ */}
        {activeTab === 'Client Reports' && (
          <div className="flex flex-col gap-5">
            <div className="grid grid-cols-5 gap-4">
              {tableData.clients.map(c => (
                <div key={c.id} className="bg-white rounded-2xl p-4 border border-slate-200">
                  <div className="flex items-center gap-2 mb-2">
                    <div className="w-7 h-7 rounded-full bg-blue-100 flex items-center justify-center text-xs font-black text-blue-600">{c.client[0]}</div>
                    <span className="text-xs  text-slate-800 leading-tight">{c.client}</span>
                  </div>
                  <strong className="text-xl font-black text-slate-900">{c.reports}</strong>
                  <span className="text-xs text-slate-400 ml-1">Reports</span>
                  <p className="text-[9px] text-slate-400 m-0 mt-1">Last: {c.last}</p>
                  <div className="mt-1">{sBadge(c.status)}</div>
                </div>
              ))}
            </div>
            <CrudTable title="Client Reports" columns={makeReportCols('client')} data={tableData.client} onAdd={makeAdd('client')} onEdit={makeEdit('client')} onDelete={makeDel('client')} />
            <CrudTable title="Top Clients" columns={clientCols} data={tableData.clients} onAdd={makeAdd('clients')} onEdit={makeEdit('clients')} onDelete={makeDel('clients')} />
          </div>
        )}

        {/* ═══════════════════ EXECUTIVE REPORTS ═══════════════════ */}
        {activeTab === 'Executive Reports' && (
          <div className="flex flex-col gap-5">
            <div className="grid grid-cols-4 gap-4">
              {[{ l: 'Executive Reports', v: '6', c: 'This Quarter' }, { l: 'Scheduled', v: '2', c: 'Upcoming' }, { l: 'Recipients', v: '12', c: 'Board Members' }, { l: 'Avg. Read Rate', v: '92%', c: 'High Engagement' }].map(s => (
                <div key={s.l} className="bg-white rounded-2xl p-4 border border-slate-200">
                  <span className="text-xs text-slate-400  block">{s.l}</span>
                  <strong className="text-2xl font-black text-slate-900 block mt-1">{s.v}</strong>
                  <span className="text-xs text-emerald-500  mt-1 block">{s.c}</span>
                </div>
              ))}
            </div>
            <CrudTable title="Executive Reports" columns={executiveCols} data={tableData.executive} onAdd={makeAdd('executive')} onEdit={makeEdit('executive')} onDelete={makeDel('executive')} />
          </div>
        )}

        {/* ═══════════════════ TEMPLATES ═══════════════════ */}
        {activeTab === 'Templates' && (
          <div className="flex flex-col gap-5">
            <div className="grid grid-cols-4 gap-4">
              {[{ l: 'Total Templates', v: '5', c: 'Active' }, { l: 'SEO Templates', v: '2', c: 'In Use' }, { l: 'Client Templates', v: '1', c: 'Active' }, { l: 'Custom Templates', v: '2', c: 'Available' }].map(s => (
                <div key={s.l} className="bg-white rounded-2xl p-4 border border-slate-200">
                  <span className="text-xs text-slate-400  block">{s.l}</span>
                  <strong className="text-2xl font-black text-slate-900 block mt-1">{s.v}</strong>
                  <span className="text-xs text-blue-500  mt-1 block">{s.c}</span>
                </div>
              ))}
            </div>
            <CrudTable title="Report Templates" columns={templateCols} data={tableData.templates} onAdd={makeAdd('templates')} onEdit={makeEdit('templates')} onDelete={makeDel('templates')} />
          </div>
        )}

        {/* ═══════════════════ SCHEDULES ═══════════════════ */}
        {activeTab === 'Schedules' && (
          <div className="flex flex-col gap-5">
            <div className="grid grid-cols-4 gap-4">
              {[{ l: 'Active Schedules', v: '4', c: 'Running' }, { l: 'Paused', v: '1', c: 'Needs Review' }, { l: 'Next Send', v: 'May 22', c: 'This Week' }, { l: 'Total Recipients', v: '15', c: 'Contacts' }].map(s => (
                <div key={s.l} className="bg-white rounded-2xl p-4 border border-slate-200">
                  <span className="text-xs text-slate-400  block">{s.l}</span>
                  <strong className="text-2xl font-black text-slate-900 block mt-1">{s.v}</strong>
                  <span className="text-xs text-emerald-500  mt-1 block">{s.c}</span>
                </div>
              ))}
            </div>
            <CrudTable title="Report Schedules" columns={scheduleCols} data={tableData.schedules} onAdd={makeAdd('schedules')} onEdit={makeEdit('schedules')} onDelete={makeDel('schedules')} />
          </div>
        )}

      </div>
    </div>
  );
}
